/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/about/about.lh
 */
export class UIAboutBase extends Laya.GWidget {
    public back!: Laya.GButton;
}

