/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { UICard } from "./UICard";
import { UIOptionButton } from "./UIOptionButton";

/**
 * resources/about/cards.lh
 */
export class UIAboutCardBase extends Laya.GWidget {
    public back!: Laya.GButton;
    public pkgs!: Laya.GComboBox;
    public cards!: Laya.GList;
    public info!: Laya.GWidget;
    public card!: UICard;
    public ttype!: UIOptionButton;
    public skill_t!: Laya.GTextField;
    public audio_male!: UIOptionButton;
    public audio_female!: UIOptionButton;
    public audio_effect!: UIOptionButton;
    public concept!: Laya.GTextField;
}

