/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { UICard } from "./UICard";
import { UIOptionButton } from "./UIOptionButton";

/**
 * resources/about/generals.lh
 */
export class UIAboutGeneralBase extends Laya.GWidget {
    public back!: Laya.GButton;
    public pkgs!: Laya.GComboBox;
    public generals!: Laya.GList;
    public info!: Laya.GWidget;
    public card!: UICard;
    public ttype!: UIOptionButton;
    public set_avatar!: UIOptionButton;
    public info_list!: Laya.GList;
    public infos!: Laya.GTextField;
    public g_enable!: Laya.GTextField;
    public g_zhulianbihe!: Laya.GTextField;
    public concept!: Laya.GTextField;
}

