/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/room/bancountry.lh
 */
export class UIBanCountryBase extends Laya.GWidget {
    public banBg!: Laya.Skeleton;
    public ban_result!: Laya.Skeleton;
    public wei_result!: Laya.Skeleton;
    public shu_result!: Laya.Skeleton;
    public wu_result!: Laya.Skeleton;
    public qun_result!: Laya.Skeleton;
    public jin_result!: Laya.Skeleton;
    public result!: Laya.GImage;
}

