/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { UICard_ViewAs } from './UICard_ViewAs';

/**
 * resources/card/card.lh
 */
export class UICardBase extends Laya.GWidget {
    public card_image!: Laya.GImage;
    public number!: Laya.GImage;
    public suit!: Laya.GImage;
    public color!: Laya.GImage;
    public transferable!: Laya.GImage;
    public viewas!: UICard_ViewAs;
    public general_image!: Laya.GImage;
    public pkgname!: Laya.GTextField;
    public border!: Laya.GImage;
    public kingdom!: Laya.GImage;
    public kingdom2!: Laya.GImage;
    public general_name!: Laya.GTextField;
    public shield!: Laya.GImage;
    public shield_label!: Laya.GTextField;
    public hps!: Laya.GBox;
    public hp_label!: Laya.GTextField;
    public zhulian!: Laya.GImage;
    public zhulian_zi!: Laya.GImage;
    public general_back!: Laya.GImage;
    public pkg_icon!: Laya.GImage;
    public img!: Laya.GImage;
    public miaoji!: Laya.GImage;
    public command_label!: Laya.GTextField;
    public command_back!: Laya.GImage;
    public canClick!: Laya.GWidget;
    public isSelected!: Laya.GImage;
    public label!: Laya.GTextField;
    public animations!: Laya.GWidget;
    public panding!: Laya.Sprite;
    public pindianlose!: Laya.Animation;
    public pindianwin!: Laya.Animation;
    public cardtag!: Laya.GImage;
    public tagtext!: Laya.GTextField;
}
