/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/card/viewas.lh
 */
export class UICard_ViewAsBase extends Laya.GImage {
    public viewas_name!: Laya.GTextField;
    public viewas_number!: Laya.GImage;
    public viewas_suit!: Laya.GImage;
}

