/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/window/cards.lh
 */
export class UIChooseCardsBase extends Laya.GWidget {
    public cards!: Laya.GBox;
}

