/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/chat/chat.lh
 */
export class UIChatBase extends Laya.GWidget {
    public inputChat!: Laya.GTextInput;
    public btn_send!: Laya.GButton;
    public btn_face!: Laya.GButton;
    public btn_random!: Laya.GButton;
    public btn_show!: Laya.GButton;
    public btn_hide!: Laya.GButton;
    public box!: Laya.GWidget;
    public fast!: Laya.GComboBox;
    public img_0!: Laya.GImage;
    public img_1!: Laya.GImage;
    public img_2!: Laya.GImage;
    public img_3!: Laya.GImage;
    public img_4!: Laya.GImage;
    public img_5!: Laya.GImage;
    public img_6!: Laya.GImage;
    public img_7!: Laya.GImage;
    public img_8!: Laya.GImage;
    public img_18!: Laya.GImage;
    public img_17!: Laya.GImage;
    public img_16!: Laya.GImage;
    public img_15!: Laya.GImage;
    public img_14!: Laya.GImage;
    public img_13!: Laya.GImage;
    public img_12!: Laya.GImage;
    public img_11!: Laya.GImage;
    public img_10!: Laya.GImage;
    public img_9!: Laya.GImage;
    public img_28!: Laya.GImage;
    public img_27!: Laya.GImage;
    public img_26!: Laya.GImage;
    public img_25!: Laya.GImage;
    public img_24!: Laya.GImage;
    public img_23!: Laya.GImage;
    public img_22!: Laya.GImage;
    public img_21!: Laya.GImage;
    public img_20!: Laya.GImage;
    public img_19!: Laya.GImage;
    public img_38!: Laya.GImage;
    public img_37!: Laya.GImage;
    public img_36!: Laya.GImage;
    public img_35!: Laya.GImage;
    public img_34!: Laya.GImage;
    public img_33!: Laya.GImage;
    public img_32!: Laya.GImage;
    public img_31!: Laya.GImage;
    public img_30!: Laya.GImage;
    public img_29!: Laya.GImage;
    public img_48!: Laya.GImage;
    public img_47!: Laya.GImage;
    public img_46!: Laya.GImage;
    public img_45!: Laya.GImage;
    public img_44!: Laya.GImage;
    public img_43!: Laya.GImage;
    public img_42!: Laya.GImage;
    public img_41!: Laya.GImage;
    public img_40!: Laya.GImage;
    public img_39!: Laya.GImage;
    public img_55!: Laya.GImage;
    public img_54!: Laya.GImage;
    public img_53!: Laya.GImage;
    public img_52!: Laya.GImage;
    public img_51!: Laya.GImage;
    public img_50!: Laya.GImage;
    public img_49!: Laya.GImage;
    public chats!: Laya.GPanel;
    public txt!: Laya.GTextField;
}

