/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/window/templete/general_single.lh
 */
export class UIChooseGeneralSingleBase extends Laya.GBox {
    public generals!: Laya.GBox;
    public head!: Laya.GImage;
}

