/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/window/templete/general_dual.lh
 */
export class UIChooseGeneralDualBase extends Laya.GBox {
    public generals!: Laya.GBox;
    public head!: Laya.GImage;
    public deputy!: Laya.GImage;
}

