/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { UIOptionButton } from "./UIOptionButton";

/**
 * resources/entry.lh
 */
export class UIEntryBase extends Laya.GWidget {
    public bg!: Laya.GImage;
    public Btn_EntryGame!: UIOptionButton;
    public Input_Server!: Laya.GTextInput;
    public Input_Account!: Laya.GTextInput;
    public Input_Password!: Laya.GTextInput;
    public Btn_Test!: UIOptionButton;
    public Btn_Lobby!: UIOptionButton;
    public txt_1!: Laya.GTextField;
    public txt!: Laya.GTextField;
    public nobgm!: Laya.GButton;
}

