/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/card/equip_self.lh
 */
export class UIEquipSelfBase extends Laya.GWidget {
    public img!: Laya.GImage;
    public number!: Laya.GImage;
    public suit!: Laya.GImage;
    public canClick!: Laya.GWidget;
    public isSelected!: Laya.GLoader;
}

