/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/card/equip.lh
 */
export class UIEquipBase extends Laya.GWidget {
    public img!: Laya.GImage;
    public number!: Laya.GImage;
    public suit!: Laya.GImage;
}

