/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { UISelfSeat } from "./UISelfSeat";
import { UIBanCountry } from "./UIBanCountry";
import { UICard } from "./UICard";

/**
 * resources/room/room_game.lh
 */
export class UIGameRoomBase extends Laya.GWidget {
    public bg!: Laya.GImage;
    public aozhan!: Laya.GWidget;
    public aozhan_ani!: Laya.Skeleton;
    public time!: Laya.GTextField;
    public round!: Laya.GWidget;
    public circle!: Laya.GTextField;
    public cardcount!: Laya.GTextField;
    public players!: Laya.GWidget;
    public selfseat!: UISelfSeat;
    public tuoguan!: Laya.GButton;
    public liaotian!: Laya.GButton;
    public shezhi!: Laya.GButton;
    public touxiang!: Laya.GButton;
    public touxiang_item!: Laya.GWidget;
    public touxiang_result!: Laya.GTextField;
    public cards!: Laya.GWidget;
    public machebg!: Laya.GWidget;
    public handbg!: Laya.GWidget;
    public handlebg!: Laya.GWidget;
    public houbeiqu!: Laya.GWidget;
    public houbeiqutxt!: Laya.GTextField;
    public houbeiqu_up!: Laya.GTextField;
    public houbeiqu_down!: Laya.GTextField;
    public markbg!: Laya.GImage;
    public markbg_!: Laya.GBox;
    public markhandbg!: Laya.GImage;
    public wuxie!: Laya.GButton;
    public fanxuan!: Laya.GButton;
    public zhengli!: Laya.GButton;
    public zhengli_item!: Laya.GWidget;
    public sort_name!: Laya.GButton;
    public sort_type!: Laya.GButton;
    public sort_suit!: Laya.GButton;
    public sort_point!: Laya.GButton;
    public windows!: Laya.GWidget;
    public log!: Laya.GWidget;
    public game_info!: Laya.GTextField;
    public btn_discard!: Laya.GButton;
    public logPanel!: Laya.GPanel;
    public logLabel!: Laya.GTextField;
    public btn_lock!: Laya.GButton;
    public stands!: Laya.GList;
    public bancountry!: UIBanCountry;
    public jxxd!: Laya.Sprite;
    public skill_name!: Laya.GTextField;
    public avatar_jxxd!: Laya.GImage;
    public playerinfo!: Laya.GWidget;
    public player_title!: Laya.GTextField;
    public player_close!: Laya.GButton;
    public player_head!: UICard;
    public player_deputy!: UICard;
    public info_list!: Laya.GList;
    public general_skills!: Laya.GWidget;
    public areaname!: Laya.GTextField;
    public general_selected!: Laya.GWidget;
    public equip_skills!: Laya.GWidget;
    //public areaname!: Laya.GTextField;
    public equip_selected!: Laya.GWidget;
    public card_note!: Laya.GTextField;
    public game_over!: Laya.GWidget;
    public mvp!: Laya.Sprite;
    public avatar_mvp!: Laya.GImage;
    public mvp_txt!: Laya.GTextField;
    public popup!: Laya.GWidget;
    public popup_pingbi!: Laya.GButton;
    public popup_jubao!: Laya.GButton;
}

