/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/card/generalhp.lh
 */
export class UIGeneralHpBase extends Laya.GWidget {
    public hp_left!: Laya.GImage;
    public hp_right!: Laya.GImage;
}

