/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { UISkillButton } from "./UISkillButton";

/**
 * resources/about/general_info_item.lh
 */
export class UIInfoItemBase extends Laya.GBox {
    public skill!: UISkillButton;
    public skill_t!: Laya.GTextField;
    public list!: Laya.GList;
}

