/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/window/items_items.lh
 */
export class UIItemItemsBase extends Laya.GWidget {
    public areabg!: Laya.GWidget;
    public areaname!: Laya.GTextField;
}

