/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { UIItemItems } from "./UIItemItems";

/**
 * resources/window/items_rows.lh
 */
export class UIItemsRowBase extends Laya.GWidget {
    public areabg!: Laya.GWidget;
    public areaname!: Laya.GTextField;
    public cards!: Laya.GBox;
    public items_items_0!: UIItemItems;
    public items_items_1!: UIItemItems;
    public items_items_2!: UIItemItems;
    public items_items_3!: UIItemItems;
    public items_items_4!: UIItemItems;
    public items_items_5!: UIItemItems;
    public items_items_6!: UIItemItems;
    public items_items_7!: UIItemItems;
    public items_items_8!: UIItemItems;
    public items_items_9!: UIItemItems;
}

