/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { UIItemsRow } from "./UIItemsRow";

/**
 * resources/window/items.lh
 */
export class UIItemsBase extends Laya.GWidget {
    public cards!: Laya.GBox;
    public items_0!: UIItemsRow;
    public items_1!: UIItemsRow;
    public items_2!: UIItemsRow;
    public items_3!: UIItemsRow;
    public items_4!: UIItemsRow;
}

