/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { UIOptionButton } from "./UIOptionButton";

/**
 * resources/lobby/item.lh
 */
export class UILobbyItemBase extends Laya.GWidget {
    public roomname!: Laya.GTextField;
    public playercount!: Laya.GTextField;
    public roomstate!: Laya.GTextField;
    public btn_joinroom!: UIOptionButton;
    public btn_standroom!: UIOptionButton;
    public btn_options!: UIOptionButton;
    public inputpassword!: Laya.GTextInput;
    public btn_confirm!: UIOptionButton;
}

