/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/load/load.lh
 */
export class UILoadBase extends Laya.GWidget {
    public bg!: Laya.GImage;
    public ProgressBar!: Laya.GProgressBar;
    public txt!: Laya.GTextField;
}

