/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { UIOptionButton } from "./UIOptionButton";

/**
 * resources/lobby/lobby.lh
 */
export class UILobbyBase extends Laya.GWidget {
    public onlinecount!: Laya.GTextField;
    public list!: Laya.GList;
    public createnode!: Laya.GWidget;
    public Input_Account!: Laya.GTextInput;
    public Input_Password!: Laya.GTextInput;
    public mode!: Laya.GComboBox;
    public choosecount!: Laya.GComboBox;
    public luckcount!: Laya.GComboBox;
    public zuobi!: Laya.GComboBox;
    public generals!: Laya.GList;
    public cards!: Laya.GList;
    public btn_create_confirm!: UIOptionButton;
    public btn_create_cancle!: UIOptionButton;
    public maxplayer!: Laya.GComboBox;
    public btn_create!: UIOptionButton;
    public btn_general!: UIOptionButton;
    public btn_card!: UIOptionButton;
    public btn_option!: UIOptionButton;
    public btn_exit!: UIOptionButton;
    public btn_user!: UIOptionButton;
    public btn_video!: UIOptionButton;
    public txt!: Laya.GTextField;
    public onlywait!: Laya.GButton;
    public input_serch!: Laya.GTextInput;
}

