/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/main.ls
 */
export class UIMainBase extends Laya.Scene {
    public pool!: Laya.GWidget;
    public layers!: Laya.GWidget;
    public windows!: Laya.GWidget;
    public prompt!: Laya.GWidget;
    public prompt_title!: Laya.GTextField;
    public prompt_confirm!: Laya.GButton;
    public prompt_cancle!: Laya.GButton;
    public model!: Laya.GWidget;
    public loading!: Laya.Sprite;
    public tips!: Laya.GWidget;
}

