/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/room/mark.lh
 */
export class UIMarkBase extends Laya.GImage {
    public value!: Laya.GTextField;
}

