/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/chat/paopao.lh
 */
export class UIPaoPaoBase extends Laya.GWidget {
    public chatLabel!: Laya.GTextField;
}

