/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { UIOptionButton } from "./UIOptionButton";
import { UITablePlayer } from "./UITablePlayer";
import { UIChat } from "./UIChat";

/**
 * resources/room/room.lh
 */
export class UIRoomBase extends Laya.GWidget {
    public bg!: Laya.GImage;
    public infoBg!: Laya.GImage;
    public roomname!: Laya.GTextField;
    public btn_look!: UIOptionButton;
    public btn_exit!: UIOptionButton;
    public btn_option!: UIOptionButton;
    public btn_setting!: UIOptionButton;
    public stands!: Laya.GList;
    public buttonBg!: Laya.GImage;
    public btn_start!: Laya.GButton;
    public btn_ready!: Laya.GButton;
    public btn_cancle!: Laya.GButton;
    public players!: Laya.GBox;
    public table_player_0!: UITablePlayer;
    public table_player_1!: UITablePlayer;
    public table_player_2!: UITablePlayer;
    public table_player_3!: UITablePlayer;
    public table_player_4!: UITablePlayer;
    public table_player_5!: UITablePlayer;
    public table_player_6!: UITablePlayer;
    public table_player_7!: UITablePlayer;
    public table_player_8!: UITablePlayer;
    public table_player_9!: UITablePlayer;
    public game!: Laya.GWidget;
    public chat!: UIChat;
    public game_settings!: Laya.GWidget;
    public title!: Laya.GTextField;
    public game_sets_close!: Laya.GButton;
    public bgm_slider!: Laya.GSlider;
    public audio_slider!: Laya.GSlider;
    public leave!: Laya.GButton;
    public eggaudio!: Laya.GButton;
    public popup_admin!: Laya.GWidget;
    public popupadmin_pingbi!: Laya.GButton;
    public popupadmin_jinyan!: Laya.GButton;
    public popupadmin_fenghao!: Laya.GButton;
    public popupadmin_jubao!: Laya.GButton;
}

