/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { UIRowItems } from "./UIRowItems";

/**
 * resources/window/rows.lh
 */
export class UIRowsBase extends Laya.GWidget {
    public cards!: Laya.GBox;
    public rows_items_0!: UIRowItems;
    public rows_items_1!: UIRowItems;
    public rows_items_2!: UIRowItems;
    public rows_items_3!: UIRowItems;
    public rows_items_4!: UIRowItems;
}

