/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/window/rows_items.lh
 */
export class UIRowItemsBase extends Laya.GWidget {
    public areabg!: Laya.GWidget;
    public areaname!: Laya.GTextField;
    public cards!: Laya.GWidget;
}

