/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/room/seat_general_dual.lh
 */
export class UISeatGeneralDualBase extends Laya.GWidget {
    public img!: Laya.GImage;
    public img_dual!: Laya.GImage;
    public skin_animation!: Laya.GWidget;
    public gname!: Laya.GTextField;
    public lock!: Laya.GImage;
    public qianfu!: Laya.GImage;
    public qianfu_icon!: Laya.GImage;
}

