/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { UISeatGeneral } from "./UISeatGeneral";
import { UISeatGeneralDual } from "./UISeatGeneralDual";
import { UIEquip } from "./UIEquip";
import { UIEquipHalf } from "./UIEquipHalf";
import { UIPaoPao } from "./UIPaoPao";

/**
 * resources/room/seat.lh
 */
export class UISeatBase extends Laya.GWidget {
    public main!: Laya.GWidget;
    public general_single!: UISeatGeneral;
    public general_head!: UISeatGeneralDual;
    public general_deputy!: UISeatGeneralDual;
    public fanmian!: Laya.GImage;
    public diezhi!: Laya.GImage;
    public inplayphase!: Laya.GImage;
    public inresponse!: Laya.GImage;
    public jiuState!: Laya.GImage;
    public indying!: Laya.GImage;
    public isSelected!: Laya.GImage;
    public diaohulishan!: Laya.GImage;
    public tip_prompt!: Laya.GTextField;
    public name_info!: Laya.GWidget;
    public name_bg!: Laya.GImage;
    public gname!: Laya.GTextField;
    public name_icon!: Laya.GImage;
    public playername!: Laya.GTextField;
    public hps!: Laya.GBox;
    public shield!: Laya.GImage;
    public shield_label!: Laya.GTextField;
    public hplabel!: Laya.GTextField;
    public equip31!: UIEquip;
    public equip32!: UIEquip;
    public equip35!: UIEquip;
    public equip36!: UIEquip;
    public equip33!: UIEquipHalf;
    public equip34!: UIEquipHalf;
    public handcard!: Laya.GImage;
    public handlabel!: Laya.GTextField;
    public seat!: Laya.GImage;
    public turnstate!: Laya.GImage;
    public camp!: Laya.GWidget;
    public guozhan_k_mark!: Laya.GWidget;
    public kingdom!: Laya.GImage;
    public ani_dashili!: Laya.Animation;
    public zhenfa_jiaji!: Laya.Animation;
    public zhenfa_icon!: Laya.Animation;
    public zhenfa_zi!: Laya.Animation;
    public guozhan_marks!: Laya.GWidget;
    public guozhan_mark_small!: Laya.GWidget;
    public s_wei!: Laya.GImage;
    public s_shu!: Laya.GImage;
    public s_wu!: Laya.GImage;
    public s_qun!: Laya.GImage;
    public s_jin!: Laya.GImage;
    public s_ye!: Laya.GImage;
    public guozhan_mark_big!: Laya.GWidget;
    public b_wei!: Laya.GImage;
    public b_shu!: Laya.GImage;
    public b_wu!: Laya.GImage;
    public b_qun!: Laya.GImage;
    public b_jin!: Laya.GImage;
    public b_ye!: Laya.GImage;
    public k_mark!: Laya.GWidget;
    public figure!: Laya.GImage;
    public canClick!: Laya.GWidget;
    public tiesuo!: Laya.Skeleton;
    public rest!: Laya.GTextField;
    public skill_name!: Laya.GTextField;
    public bprompt!: Laya.GTextField;
    public handbg!: Laya.GWidget;
    public hand_label!: Laya.GTextField;
    public death!: Laya.GImage;
    public timebar!: Laya.GProgressBar;
    public think_prompt!: Laya.GTextField;
    public judges!: Laya.GBox;
    public marks!: Laya.GBox;
    public images!: Laya.GBox;
    public paopao!: UIPaoPao;
    public menu!: Laya.GWidget;
    public player_info!: Laya.GButton;
    public menu_jubao!: Laya.GButton;
    public menu_pingbi!: Laya.GButton;
    public menu_close!: Laya.GButton;
    public egg!: Laya.GImage;
    public flower!: Laya.GImage;
    public aa!: Laya.Animation;
}

