/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/room/seat_general.lh
 */
export class UISeatGeneralBase extends Laya.GWidget {
    public img!: Laya.GImage;
    public skin_animation!: Laya.GWidget;
    public lock!: Laya.GImage;
    public qianfu!: Laya.GImage;
    public qianfu_icon!: Laya.GImage;
}

