/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/room/selfseat_general.lh
 */
export class UISelfSeatGeneralBase extends Laya.GWidget {
    public img!: Laya.GImage;
    public skin_animation!: Laya.GWidget;
    public namebg!: Laya.GImage;
    public gname!: Laya.GTextField;
    public name_icon!: Laya.GImage;
    public lock!: Laya.GImage;
    public qianfu!: Laya.GImage;
    public qianfu_icon!: Laya.GImage;
    public fanmian!: Laya.GImage;
    public diezhi!: Laya.GImage;
    public inplayphase!: Laya.GImage;
    public inresponse!: Laya.GImage;
    public jiuState!: Laya.GImage;
    public indying!: Laya.GImage;
    public isSelected!: Laya.GImage;
    public diaohulishan!: Laya.GImage;
    public tip_prompt!: Laya.GTextField;
    public skills!: Laya.GBox;
}

