/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { UIEquipSelf } from "./UIEquipSelf";
import { UISelfSeatGeneral } from "./UISelfSeatGeneral";
import { UIPaoPao } from "./UIPaoPao";

/**
 * resources/room/selfseat.lh
 */
export class UISelfSeatBase extends Laya.GWidget {
    public main!: Laya.GWidget;
    public equip31!: UIEquipSelf;
    public equip32!: UIEquipSelf;
    public equip35!: UIEquipSelf;
    public equip33!: UIEquipSelf;
    public equip34!: UIEquipSelf;
    public equip36!: UIEquipSelf;
    public baseBg!: Laya.GImage;
    public seat!: Laya.GImage;
    public handcard!: Laya.GImage;
    public handlabel!: Laya.GTextField;
    public camp!: Laya.GWidget;
    public guozhan_k_mark!: Laya.GWidget;
    public kingdom!: Laya.GImage;
    public ani_dashili!: Laya.Animation;
    public zhenfa_jiaji!: Laya.Animation;
    public zhenfa_icon!: Laya.Animation;
    public zhenfa_zi!: Laya.Animation;
    public k_mark!: Laya.GWidget;
    public figure!: Laya.GImage;
    public turnstate!: Laya.GImage;
    public general_head!: UISelfSeatGeneral;
    public general_deputy!: UISelfSeatGeneral;
    public canClick!: Laya.GWidget;
    public hps!: Laya.GBox;
    public shield!: Laya.GImage;
    public shield_label!: Laya.GTextField;
    public hplabel!: Laya.GTextField;
    public marks!: Laya.GBox;
    public nameBg!: Laya.GImage;
    public playername!: Laya.GTextField;
    public tiesuo!: Laya.Skeleton;
    public skill_name!: Laya.GTextField;
    public bprompt!: Laya.GTextField;
    public judges!: Laya.GBox;
    public skills!: Laya.GBox;
    public none_skills!: Laya.GWidget;
    public prompt!: Laya.GTextField;
    public timebar!: Laya.GProgressBar;
    public think_prompt!: Laya.GTextField;
    public options!: Laya.GBox;
    public buttons!: Laya.GWidget;
    public confirm!: Laya.GButton;
    public recast!: Laya.GButton;
    public cancle!: Laya.GButton;
    public end!: Laya.GButton;
    public confirm_skill!: Laya.GButton;
    public cancle_skill!: Laya.GButton;
    public death!: Laya.GImage;
    public images!: Laya.GBox;
    public paopao!: UIPaoPao;
    public looking!: Laya.GImage;
    public tuoguaning!: Laya.GImage;
    public rest!: Laya.GTextField;
}

