/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/about/skill_audio.lh
 */
export class UISkillAudioBase extends Laya.GWidget {
    public txt!: Laya.GTextField;
}

