/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/buttons/skill.lh
 */
export class UISkillButtonBase extends Laya.GButton {
    public img!: Laya.GImage;
    public avatar!: Laya.GImage;
    public title!: Laya.GTextField;
    public isSelected!: Laya.GLoader;
}

