/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { UIPaoPao } from "./UIPaoPao";
import { UIOptionButton } from "./UIOptionButton";

/**
 * resources/room/table_player.lh
 */
export class UITablePlayerBase extends Laya.GWidget {
    public img!: Laya.GImage;
    public avatar!: Laya.GImage;
    public info!: Laya.GWidget;
    public infotxt!: Laya.GTextField;
    public playername!: Laya.GTextField;
    public state!: Laya.GImage;
    public paopao!: UIPaoPao;
    public btn_tick!: UIOptionButton;
}

