/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/baseui/toast/toast.lh
 */
export class UIToastBase extends Laya.Sprite {
    public text!: Laya.GTextField;
}

