/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { UIOptionButton } from "./UIOptionButton";

/**
 * resources/about/video.lh
 */
export class UIVideoBase extends Laya.GWidget {
    public back!: Laya.GButton;
    public list!: Laya.GList;
    public btn_load!: UIOptionButton;
    public btn_clear!: UIOptionButton;
}

