/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { UIOptionButton } from "./UIOptionButton";

/**
 * resources/about/video_item.lh
 */
export class UIVideoItemBase extends Laya.GWidget {
    public roomname!: Laya.GTextField;
    public btn_watch!: UIOptionButton;
    public btn_save!: UIOptionButton;
}

