/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { UIChooseGeneralDual } from "./UIChooseGeneralDual";
import { UIChooseGeneralSingle } from "./UIChooseGeneralSingle";
import { UIRows } from "./UIRows";
import { UIChooseCards } from "./UIChooseCards";
import { UIItems } from "./UIItems";

/**
 * resources/window/window.lh
 */
export class UIWindowBase extends Laya.GWidget {
    public title!: Laya.GTextField;
    public close!: Laya.GButton;
    public content!: Laya.GPanel;
    public timebar!: Laya.GProgressBar;
    public prompt!: Laya.GTextField;
    public buttons!: Laya.GBox;
    public content_pool!: Laya.GWidget;
    public general_dual!: UIChooseGeneralDual;
    public general_single!: UIChooseGeneralSingle;
    public rows!: UIRows;
    public cards!: UIChooseCards;
    public items!: UIItems;
}

