import { RoomOption } from './core/types';

export const ServerConfig = {
    // host: '192.168.0.102',
    host: '47.93.84.143',
    port: 12699,
    res_url: 'http://res.resgs.com',
};

export const playerPos: {
    [key: string]: {
        [key: number]: { x: number; y: number; scale: number }[];
    };
} = {
    default: {
        1: [],
        2: [{ x: 959, y: 150, scale: 1.5 }],
        3: [
            { x: 1261, y: 150, scale: 1.5 },
            { x: 604, y: 150, scale: 1.5 },
        ],
        4: [
            { x: 1763, y: 500, scale: 1.5 },
            { x: 959, y: 150, scale: 1.5 },
            { x: 130, y: 500, scale: 1.5 },
        ],
        5: [
            { x: 1763, y: 500, scale: 1.5 },
            { x: 1261, y: 150, scale: 1.5 },
            { x: 604, y: 150, scale: 1.5 },
            { x: 130, y: 500, scale: 1.5 },
        ],
        6: [
            { x: 1763, y: 500, scale: 1.5 },
            { x: 1411, y: 150, scale: 1.5 },
            { x: 954, y: 150, scale: 1.5 },
            { x: 497, y: 150, scale: 1.5 },
            { x: 130, y: 500, scale: 1.5 },
        ],
        7: [
            { x: 1763, y: 500, scale: 1.5 },
            { x: 1458, y: 150, scale: 1.5 },
            { x: 1111, y: 150, scale: 1.5 },
            { x: 764, y: 150, scale: 1.5 },
            { x: 417, y: 150, scale: 1.5 },
            { x: 130, y: 500, scale: 1.5 },
        ],
        8: [
            { x: 1763, y: 500, scale: 1.5 },
            { x: 1485, y: 150, scale: 1.5 },
            { x: 1218, y: 150, scale: 1.5 },
            { x: 951, y: 150, scale: 1.5 },
            { x: 684, y: 150, scale: 1.5 },
            { x: 417, y: 150, scale: 1.5 },
            { x: 130, y: 500, scale: 1.5 },
        ],
        9: [
            { x: 1763, y: 570, scale: 1.5 },
            { x: 1763, y: 270, scale: 1.5 },
            { x: 1458, y: 150, scale: 1.5 },
            { x: 1111, y: 150, scale: 1.5 },
            { x: 764, y: 150, scale: 1.5 },
            { x: 417, y: 150, scale: 1.5 },
            { x: 130, y: 270, scale: 1.5 },
            { x: 130, y: 570, scale: 1.5 },
        ],
        10: [
            { x: 1763, y: 570, scale: 1.5 },
            { x: 1763, y: 270, scale: 1.5 },
            { x: 1485, y: 150, scale: 1.5 },
            { x: 1218, y: 150, scale: 1.5 },
            { x: 951, y: 150, scale: 1.5 },
            { x: 684, y: 150, scale: 1.5 },
            { x: 417, y: 150, scale: 1.5 },
            { x: 130, y: 270, scale: 1.5 },
            { x: 130, y: 570, scale: 1.5 },
        ],
    },
};

export const testPlayers = [
    {
        playerId: 'alone',
        username: 'alone player',
        avatar: '',
        total: 0,
        win: 0,
        escape: 0,
    },
    {
        playerId: 'test#1',
        username: 'test player#1',
        avatar: '',
        total: 0,
        win: 0,
        escape: 0,
    },
    {
        playerId: 'test#2',
        username: 'test player#2',
        avatar: '',
        total: 0,
        win: 0,
        escape: 0,
    },
    {
        playerId: 'test#3',
        username: 'test player#3',
        avatar: '',
        total: 0,
        win: 0,
        escape: 0,
    },
    {
        playerId: 'test#4',
        username: 'test player#4',
        avatar: '',
        total: 0,
        win: 0,
        escape: 0,
    },
    {
        playerId: 'test#5',
        username: 'test player#5',
        avatar: '',
        total: 0,
        win: 0,
        escape: 0,
    },
    {
        playerId: 'test#6',
        username: 'test player#6',
        avatar: '',
        total: 0,
        win: 0,
        escape: 0,
    },
    {
        playerId: 'test#7',
        username: 'test player#7',
        avatar: '',
        total: 0,
        win: 0,
        escape: 0,
    },
    {
        playerId: 'test#8',
        username: 'test player#8',
        avatar: '',
        total: 0,
        win: 0,
        escape: 0,
    },
    {
        playerId: 'test#9',
        username: 'test player#9',
        avatar: '',
        total: 0,
        win: 0,
        escape: 0,
    },
];

export const fastAudio = [
    '能不能快一点啊，兵贵神速啊',
    '主公，别开枪，自己人',
    '小内在不跳，后面还怎么玩啊',
    '你们怎么忍心，就这么让我酱油了',
    '我，我惹你们了吗',
    '姑娘，你真是条汉子',
    '三十六计走为上，容我去去便回',
    '人心散了，队伍不好带啊',
    '昏君，昏君啊',
    '风吹鸡蛋壳，牌去人安乐',
    '小内啊，您老悠着点',
    '不好意思，刚才卡了',
    '你可以打的在烂一点吗',
    '哥们，给力点行吗',
    '哥，交个朋友吧',
    '妹子，交个朋友吧',
    '我从未见过如此厚颜无耻之人',
    '这波，不亏',
    '请收下我的膝盖',
    '你咋不上天呢',
    '放开我的队友，冲我来',
    '你随便杀，闪不了算我输',
    '见证奇迹的时刻到了',
    '别乱出牌，看清楚我技能',
    '不急，回复状态慢慢打',
    '不用无懈',
    '合作愉快',
    '有桃',
    '注意，控距离',
    '注意，铁索连环状态',
    '注意，我的手牌',
    '注意，我头上的延时锦囊',
    '注意，有读条',
];

export const RoomOptions: { [key: string]: RoomOption } = {
    ['wars']: {
        name: '[国-官晋]',
        password: '',
        mode: 'wars',
        playerCountMax: 10,
        responseTime: 12,
        chooseGeneralCount: 5,
        luckyCardCount: 0,
        extensions: ['WarsStandardCards', 'WarsPowerCards'],
        generals: [
            'default.shibingn',
            'default.shibingv',

            'wars.caocao',
            'wars.simayi',
            'wars.xiahoudun',
            'wars.zhangliao',
            'wars.xuchu',
            'wars.guojia',
            'wars.zhenji',
            'wars.xiahouyuan',
            'wars.zhanghe',
            'wars.xuhuang',
            'wars.caoren',
            'wars.dianwei',
            'wars.xunyu',
            'wars.caopi',
            'wars.yuejin',

            'wars.liubei',
            'wars.guanyu',
            'wars.zhangfei',
            'wars.zhugeliang',
            'wars.zhaoyun',
            'wars.machao',
            'wars.huangyueying',
            'wars.v2025.huangzhong',
            'wars.weiyan',
            'wars.pangtong',
            'wars.wolong',
            'wars.liushan',
            'wars.menghuo',
            'wars.zhurong',
            'wars.ganfuren',

            'wars.sunquan',
            'wars.ganning',
            'wars.lvmeng',
            'wars.huanggai',
            'wars.zhouyu',
            'wars.daqiao',
            'wars.v2025.luxun',
            'wars.sunshangxiang',
            'wars.sunjian',
            'wars.xiaoqiao',
            'wars.taishici',
            'wars.zhoutai',
            'wars.lusu',
            'wars.zhangzhaozhanghong',
            'wars.dingfeng',

            'wars.huatuo',
            'wars.lvbu',
            'wars.diaochan',
            'wars.yuanshao',
            'wars.yanliangwenchou',
            'wars.jiaxu',
            'wars.pangde',
            'wars.zhangjiao',
            'wars.caiwenji',
            'wars.mateng',
            'wars.kongrong',
            'wars.v2025.jiling',
            'wars.v2025.tianfeng',
            'wars.v2025.panfeng',
            'wars.zoushi',

            'wars.dengai',
            'wars.caohong',
            'wars.jiangwei',
            'wars.jiangwanfeiyi',
            'wars.xusheng',
            'wars.jiangqin',
            'wars.yuji',
            'wars.hetaihou',

            'wars.lidian',
            'wars.zangba',
            'wars.madai',
            'wars.mifuren',
            'wars.sunce',
            'wars.chenwudongxi',
            'wars.dongzhuo',
            'wars.zhangren',

            'wars.xunyou',
            'wars.bianfuren',
            'wars.masu',
            'wars.shamoke',
            'wars.lvfan',
            'wars.lingtong',
            'wars.zuoci',
            'wars.lijueguosi',

            'wars.yujin',
            'wars.cuiyanmaojie',
            'wars.fazheng',
            'wars.wangping',
            'wars.wuguotai',
            'wars.lukang',
            'wars.yuanshu',
            'wars.zhangxiu',

            'wars.huaxin',
            'wars.yanghu_wei',
            'wars.zongyu',
            'wars.dengzhi',
            'wars.luyusheng',
            'wars.fengxi',
            'wars.miheng',
            'wars.xunchen',

            'wars.lord_caocao',
            'wars.lord_liubei',
            'wars.lord_sunquan',
            'wars.lord_zhangjiao',

            'wars.simayi_jin',
            'wars.zhangchunhua_jin',
            'wars.simashi',
            'wars.simazhao',
            'wars.simazhou',
            'wars.simaliang',
            'wars.simalun',
            'wars.shibao',
            'wars.yanghuiyu',
            'wars.wangyuanji',
            'wars.weiguan',
            'wars.jiachong',
            'wars.guohuai_jin',
            'wars.wangjun',
            'wars.malong',

            'wars.yanghu',
            'wars.duyu',
            'wars.zhanghuyuechen',
            'wars.wenyang',
            'wars.wangxiang',
            'wars.baifuren',
            'wars.yangjun',
            'wars.sunxiu_jin',

            'wars.jiananfeng',
            'wars.xiahouhui',

            'wars.lord_simayi',

            'wars.zhonghui',
        ],
        settings: {
            datamode: 'wars_temp_jin',
            lordEquip: 'true',
            banCountry: 'true',
            // zuobi: 'true',
            randomSeat: 'true',
            watchNext: 'true',
            test: 'true',
        },
    },
    ['wars_xl']: {
        name: '[国-西凉晋]',
        password: '',
        mode: 'wars',
        playerCountMax: 10,
        responseTime: 12,
        chooseGeneralCount: 5,
        luckyCardCount: 0,
        extensions: ['WarsStandardCards', 'WarsPowerCards'],
        generals: [
            'default.shibingn',
            'default.shibingv',

            'wars.caocao',
            'wars.simayi',
            'wars.xiahoudun',
            'wars.zhangliao',
            'wars.xuchu',
            'wars.guojia',
            'wars.zhenji',
            'wars.xiahouyuan',
            'wars.zhanghe',
            'wars.xuhuang',
            'wars.caoren',
            'wars.dianwei',
            'wars.xunyu',
            'wars.caopi',
            'wars.yuejin',

            'wars.liubei',
            'wars.guanyu',
            'wars.zhangfei',
            'wars.zhugeliang',
            'wars.zhaoyun',
            'wars.machao',
            'wars.huangyueying',
            'wars.v2025.huangzhong',
            'wars.weiyan',
            'wars.pangtong',
            'wars.wolong',
            'wars.liushan',
            'wars.menghuo',
            'wars.zhurong',
            'wars.ganfuren',

            'wars.sunquan',
            'wars.ganning',
            'wars.lvmeng',
            'wars.huanggai',
            'wars.zhouyu',
            'wars.daqiao',
            'wars.v2025.luxun',
            'wars.sunshangxiang',
            'wars.sunjian',
            'wars.xiaoqiao',
            'wars.taishici',
            'wars.zhoutai',
            'wars.lusu',
            'wars.zhangzhaozhanghong',
            'wars.dingfeng',

            'wars.huatuo',
            'wars.lvbu',
            'wars.diaochan',
            'wars.yuanshao',
            'wars.yanliangwenchou',
            'wars.jiaxu',
            'wars.pangde',
            'wars.zhangjiao',
            'wars.caiwenji',
            'wars.mateng',
            'wars.kongrong',
            'wars.v2025.jiling',
            'wars.v2025.tianfeng',
            'wars.v2025.panfeng',
            'wars.zoushi',

            'wars.lord_caocao',
            'wars.lord_liubei',
            'wars.lord_sunquan',
            'wars.lord_zhangjiao',

            'xl.simayan',
            'xl.simazhao',
            'xl.wangyuanji',
            'xl.wenyang',
            'xl.simafu',
            'xl.simawang',
            'xl.zhanghua',
            'xl.peixiu',
            'xl.wangjun',
            'xl.hufen',
            'xl.xiahouhui',
            'xl.wanghun',
            'xl.zhongyan',
            'xl.tangbin',
            'xl.huliehuyuan',

            'xl.lord_simayan',

            'wars.dengai',
            'wars.caohong',
            'wars.jiangwei',
            'wars.jiangwanfeiyi',
            'wars.xusheng',
            'wars.jiangqin',
            'wars.yuji',
            'wars.hetaihou',

            'wars.lidian',
            'wars.zangba',
            'wars.madai',
            'wars.mifuren',
            'wars.sunce',
            'wars.chenwudongxi',
            'wars.dongzhuo',
            'wars.zhangren',

            'wars.xunyou',
            'wars.bianfuren',
            'wars.masu',
            'wars.shamoke',
            'wars.lvfan',
            'wars.lingtong',
            'wars.zuoci',
            'wars.lijueguosi',

            'wars.yujin',
            'wars.cuiyanmaojie',
            'wars.fazheng',
            'wars.wangping',
            'wars.wuguotai',
            'wars.lukang',
            'wars.yuanshu',
            'wars.zhangxiu',

            'xl.yanghu',
            'xl.duyu',
            'xl.weiguan',
            'xl.zhouzhi',
            'xl.malong',
            'xl.shantao',
            'xl.jishao',
            'xl.simashi',
            'xl.yanghuiyu',

            'wars.huaxin',
            'wars.yanghu_wei',
            'wars.zongyu',
            'wars.dengzhi',
            'wars.luyusheng',
            'wars.fengxi',
            'wars.miheng',
            'wars.xunchen',
            'xl.wangxiang',
            'xl.luji_jin',
            'xl.luyun',

            'xl.caozhi',
            'xl.cuifei',
            'xl.guansuo',
            'xl.wangtaowangyue',
            'xl.zhuju',
            'xl.sunluyu',
            'xl.zhangze',
            'xl.chenhuiqian',
            'xl.shichong',
            'xl.lvzhu',

            'wars.zhonghui',
        ],
        settings: {
            datamode: 'wars_temp_xl',
            lordEquip: 'true',
            banCountry: 'true',
            randomSeat: 'true',
            watchNext: 'true',
        },
    },
    ['wars_test']: {
        name: '[国-测试]',
        password: '',
        mode: 'wars',
        playerCountMax: 10,
        responseTime: 12,
        chooseGeneralCount: 6,
        luckyCardCount: 0,
        extensions: ['WarsStandardCards', 'WarsPowerCards'],
        generals: [
            'default.shibingn',
            'default.shibingv',

            'wars.caocao',
            'wars.simayi',
            'wars.xiahoudun',
            'wars.zhangliao',
            'wars.xuchu',
            'wars.guojia',
            'wars.zhenji',
            'wars.xiahouyuan',
            'wars.zhanghe',
            'wars.xuhuang',
            'wars.caoren',
            'wars.dianwei',
            'wars.xunyu',
            'wars.caopi',
            'wars.yuejin',

            'wars.liubei',
            'wars.guanyu',
            'wars.zhangfei',
            'wars.zhugeliang',
            'wars.zhaoyun',
            'wars.machao',
            'wars.huangyueying',
            'wars.huangzhong',
            'wars.weiyan',
            'wars.pangtong',
            'wars.wolong',
            'wars.liushan',
            'wars.menghuo',
            'wars.zhurong',
            'wars.ganfuren',

            'wars.sunquan',
            'wars.ganning',
            'wars.lvmeng',
            'wars.huanggai',
            'wars.zhouyu',
            'wars.daqiao',
            'wars.luxun',
            'wars.sunshangxiang',
            'wars.sunjian',
            'wars.xiaoqiao',
            'wars.taishici',
            'wars.zhoutai',
            'wars.lusu',
            'wars.zhangzhaozhanghong',
            'wars.dingfeng',

            'wars.huatuo',
            'wars.lvbu',
            'wars.diaochan',
            'wars.yuanshao',
            'wars.yanliangwenchou',
            'wars.jiaxu',
            'wars.pangde',
            'wars.zhangjiao',
            'wars.caiwenji',
            'wars.mateng',
            'wars.kongrong',
            'wars.jiling',
            'wars.tianfeng',
            'wars.panfeng',
            'wars.zoushi',

            'wars.dengai',
            'wars.caohong',
            'wars.jiangwei',
            'wars.jiangwanfeiyi',
            'wars.xusheng',
            'wars.jiangqin',
            'wars.yuji',
            'wars.hetaihou',

            'wars.lidian',
            'wars.zangba',
            'wars.madai',
            'wars.mifuren',
            'wars.sunce',
            'wars.chenwudongxi',
            'wars.dongzhuo',
            'wars.zhangren',

            'wars.xunyou',
            'wars.bianfuren',
            'wars.masu',
            'wars.shamoke',
            'wars.lvfan',
            'wars.lingtong',
            'wars.zuoci',
            'wars.lijueguosi',

            'wars.yujin',
            'wars.cuiyanmaojie',
            'wars.fazheng',
            'wars.wangping',
            'wars.wuguotai',
            'wars.lukang',
            'wars.yuanshu',
            'wars.zhangxiu',

            'wars.huaxin',
            'wars.yanghu_wei',
            'wars.zongyu',
            'wars.dengzhi',
            'wars.luyusheng',
            'wars.fengxi',
            'wars.miheng',
            'wars.xunchen',

            'wars.lord_caocao',
            'wars.lord_liubei',
            'wars.lord_sunquan',
            'wars.lord_zhangjiao',

            'xl.simayan',
            'xl.simazhao',
            'xl.wangyuanji',
            'xl.wenyang',
            'xl.simafu',
            'xl.simawang',
            'xl.zhanghua',
            'xl.peixiu',
            'xl.wangjun',
            'xl.hufen',
            'xl.xiahouhui',
            'xl.wanghun',
            'xl.zhongyan',
            'xl.tangbin',
            'xl.huliehuyuan',

            'xl.yanghu',
            'xl.duyu',
            'xl.weiguan',
            'xl.zhouzhi',
            'xl.malong',
            'xl.shantao',
            'xl.jishao',
            'xl.simashi',
            'xl.yanghuiyu',

            'xl.wangxiang',
            'xl.luji_jin',
            'xl.luyun',

            'xl.lord_simayan',

            'xl.caozhi',
            'xl.cuifei',
            'xl.guansuo',
            'xl.wangtaowangyue',
            'xl.zhuju',
            'xl.sunluyu',
            'xl.zhangze',
            'xl.chenhuiqian',
            'xl.shichong',
            'xl.lvzhu',
        ],
        settings: {
            datamode: 'wars_temp_test',
            lordEquip: 'true',
            banCountry: 'true',
            zuobi: 'true',
            randomSeat: 'true',
            watchNext: 'true',
            test: 'true',
        },
    },
    ['doudizhu_test']: {
        name: '[斗-测试]',
        password: '',
        mode: 'doudizhu',
        playerCountMax: 3,
        responseTime: 12,
        chooseGeneralCount: 3,
        luckyCardCount: 0,
        extensions: ['StandardCards', 'StandardExCards', 'JunZhengCards'],
        generals: [
            'default.shibingn',
            'default.shibingv',

            'wars.caocao',
            'wars.simayi',
            'wars.xiahoudun',
            'wars.zhangliao',
            'wars.xuchu',
            'wars.guojia',
            'wars.zhenji',
            'wars.xiahouyuan',
            'wars.zhanghe',
            'wars.xuhuang',
            'wars.caoren',
            'wars.dianwei',
            'wars.xunyu',
            'wars.caopi',
            'wars.yuejin',

            'wars.liubei',
            'wars.guanyu',
            'wars.zhangfei',
            'wars.zhugeliang',
            'wars.zhaoyun',
            'wars.machao',
            'wars.huangyueying',
            'wars.huangzhong',
            'wars.weiyan',
            'wars.pangtong',
            'wars.wolong',
            'wars.liushan',
            'wars.menghuo',
            'wars.zhurong',
            'wars.ganfuren',

            'wars.sunquan',
            'wars.ganning',
            'wars.lvmeng',
            'wars.huanggai',
            'wars.zhouyu',
            'wars.daqiao',
            'wars.sunshangxiang',
            'wars.sunjian',
            'wars.xiaoqiao',
            'wars.taishici',
            'wars.zhoutai',
            'wars.lusu',
            'wars.zhangzhaozhanghong',
            'wars.dingfeng',

            'wars.huatuo',
            'wars.lvbu',
            'wars.diaochan',
            'wars.yuanshao',
            'wars.yanliangwenchou',
            'wars.jiaxu',
            'wars.pangde',
            'wars.zhangjiao',
            'wars.caiwenji',
            'wars.jiling',
            'wars.panfeng',

            'wars.hetaihou',

            'wars.lidian',
            'wars.madai',

            'wars.xunyou',
            'wars.masu',
            'wars.shamoke',
            'wars.lingtong',
            'wars.lijueguosi',

            'wars.yujin',
            'wars.lukang',
            'wars.zhangxiu',

            'wars.shibao',
            'wars.wangjun',

            'wars.wangxiang',
            'wars.sunxiu_jin',

            'wars.jiananfeng',
            'wars.xiahouhui',

            'caomao',
            'mobile.shichangshi',
            'cs_zhangrang',
            'cs_zhaozhong',
            'cs_sunzhang',
            'cs_bilan',
            'cs_xiayun',
            'cs_hankui',
            'cs_lisong',
            'cs_duangui',
            'cs_guosheng',
            'cs_gaowang',
        ],
        settings: {
            datamode: 'doudizhu_test',
            // zuobi: 'true',
            randomSeat: 'true',
            // watchNext: 'true',
        },
    },
};
