export const ScenesEnum = {
    Load: 'resources/load/load.lh',
    Entry: 'resources/entry.lh',
    Lobby: 'resources/lobby/lobby.lh',
    Room: 'resources/room/room.lh',
    AboutGeneral: 'resources/about/generals.lh',
    AboutCard: 'resources/about/cards.lh',
    About: 'resources/about/about.lh',
    Video: 'resources/about/video.lh',
};

export const res = {
    pres: [
        'resources/baseui/Checkbox.lh',
        'resources/baseui/ComboBox.lh',
        'resources/baseui/ComboBox_dropdow.lh',
        'resources/baseui/ScrollBar.lh',
        'resources/baseui/loading/loading.lh',
        'resources/baseui/loading/loading.mcc',
        'resources/baseui/loading/loading.mc',
        'resources/baseui/toast/toast.lh',
    ],
    scenes: [
        'resources/about/about.lh',
        'resources/about/cards.lh',
        'resources/about/generals.lh',
        'resources/about/video.lh',

        'resources/lobby/lobby.lh',
        'resources/room/room.lh',
        'resources/room/room_game.lh',
        'resources/entry.lh',
    ],
    prefabs: [
        'resources/buttons/close.lh',
        'resources/buttons/option.lh',
        'resources/buttons/skill.lh',
        'resources/buttons/top_green.lh',
        'resources/buttons/top_red.lh',
        'resources/buttons/window_btn_1.lh',
        'resources/buttons/window_btn_2.lh',

        'resources/card/card.lh',
        'resources/card/equip.lh',
        'resources/card/equip_half.lh',
        'resources/card/equip_self.lh',
        'resources/card/generalhp.lh',
        'resources/card/viewas.lh',

        'resources/chat/chat.lh',
        'resources/chat/paopao.lh',

        'resources/lobby/item.lh',

        'resources/room/bancountry.lh',
        'resources/room/icon.lh',
        'resources/room/mark.lh',
        'resources/room/seat.lh',
        'resources/room/seat_general.lh',
        'resources/room/seat_general_dual.lh',
        'resources/room/selfseat.lh',
        'resources/room/selfseat_general.lh',
        'resources/room/skin_animation.lh',
        'resources/room/table_player.lh',
        'resources/room/textmark.lh',

        'resources/window/cards.lh',
        'resources/window/items.lh',
        'resources/window/items_items.lh',
        'resources/window/items_rows.lh',
        'resources/window/rows.lh',
        'resources/window/rows_items.lh',
        'resources/window/window.lh',
        'resources/window/templete/general_dual.lh',
        'resources/window/templete/general_single.lh',

        'resources/about/general_info_item.lh',
        'resources/about/skill_audio.lh',
        'resources/about/video_item.lh',

        //ani
        // 'resources/room/cc_ani/caomao_skill.lh',
        // 'resources/room/cc_ani/shenlusu_skill.lh',
        // 'resources/room/cc_ani/shichangshi_skill.lh',
        // 'resources/room/cc_ani/shitaishici_skill.lh',
    ],
    images: [
        'resources/logo.png',
        'resources/background/frameBg.jpg',
        'resources/background/gameBg.jpg',
        'resources/background/hallBg.png',

        //每个资源包加载一个小图
        'resources/baseui/cmn_checkbox_normal.png',
        'resources/buttons/texture/awake.png',
        'resources/card/texture/card/card-back-guozhan.png',
        'resources/chat/texture/chat_btn_down_down.png',
        'resources/lobby/texture/hall_room_jinyan_mark.png',
        'resources/room/texture/daoju/egg0.png',
        'resources/window/texture/dest-seat.png',
    ],
    fonts: [
        'resources/font/DroidSansFallback.ttf',
        'resources/font/fontawesome-webfont.ttf',
        'resources/font/FZLBGBK.ttf',
        'resources/font/FZLE.ttf',
        'resources/font/FZLTCHJW.ttf',
        'resources/font/HYSHANGWEISHOUSHUW.ttf',
        'resources/font/SIMHEI.ttf',
        'resources/font/SIMKAI.ttf',
        'resources/font/SIMLI.ttf',
        'resources/font/STXINGKA.ttf',
    ],
    spines: [
        'resources/animation/aozhan/aozhan.json',
        'resources/animation/aozhanbg/aozhan_huo.json',
        'resources/animation/biaojichufa/numChange.json',
        'resources/animation/border/qy_tx_jinengfadong.json',
        'resources/animation/egg/Ss_BiaoQing_huiqi.json',
        'resources/animation/equip1/SSequip.json',
        'resources/animation/face/meigui/Ss_BiaoQing_PengBei_meigui.json',
        'resources/animation/face/pengbei/Ss_BiaoQing_PengBei.json',
        'resources/animation/flower/Ss_BiaoQing_meihuabaokai.json',
        'resources/animation/fuhuo/aar_huanhua_fuhuo.json',
        'resources/animation/generlas/caomao/juejin/SS_cmskill.skel',
        'resources/animation/generlas/caomao/juejin_mask/SS_cmmask.skel',
        'resources/animation/generlas/caomao/state2_beijing/BeiJing.json',
        'resources/animation/generlas/caomao/state2_skin/XingXiang.json',
        'resources/animation/generlas/shenlusu/skill/SS_jn_shenlusu.json',
        'resources/animation/generlas/shenlusu/wujiang/Ss_Slusu_wujiang.json',
        'resources/animation/generlas/shichangshi/bagua/SS_scs_bagua.json',
        'resources/animation/generlas/shichangshi/bg1/SS_scs_bgfw.json',
        'resources/animation/generlas/shichangshi/bg2/SS_scs_bgrw.json',
        'resources/animation/generlas/shichangshi/effect/SS_scs_guihuo.json',
        'resources/animation/generlas/shitaishici/SS_taishici_jineng.json',
        'resources/animation/heisha/effect_heisha.json',
        'resources/animation/hongsha/effect_hongsha.json',
        'resources/animation/huanfu/huanfu.json',
        'resources/animation/huanhua_bagua/aar_huanhua_bagua.json',
        'resources/animation/huifu_number/qy_tx_huifushuzi.json',
        'resources/animation/huixue/effect_zhiliao.json',
        'resources/animation/huosha/effect_huosha.json',
        'resources/animation/jiu/effect_jiu.json',
        'resources/animation/jiu_pro/qy_tx_zhiliao_jiu.json',
        'resources/animation/jueding_xianding/jxxd.json',
        'resources/animation/kaizhan/effect_youxikaishi_SZNdjj.json',
        'resources/animation/leisha/effect_leisha.json',
        'resources/animation/mingguangkai1/Ss_mgk_fire.json',
        'resources/animation/mingguangkai2/Ss_mgk_tslh.json',
        'resources/animation/mvp/qy_quanchangzuijia.json',
        'resources/animation/panding/effect_panding_SZN.json',
        'resources/animation/sanjianliangrendao/Ss_Gz_SanJianLiangRenDao.json',
        'resources/animation/save/SZN_jiuwo.json',
        'resources/animation/shandianshoushang/qy_tx_shandianshouji.json',
        'resources/animation/shanghai_number/qy_tx_shanghaishuzi.json',
        'resources/animation/shesha/effect_shesha.json',
        'resources/animation/shiming/qy_effect_shimingji.json',
        'resources/animation/shoushang/effect_shoujidonghua.json',
        'resources/animation/switch/qizheng.json',
        'resources/animation/taipingyaoshu1/Ss_taipingyaoshu_1.skel',
        'resources/animation/taipingyaoshu2/effect_taipingyaoshu_xiexia.json',
        'resources/animation/tao/effect_tao.json',
        'resources/animation/tengjia1/effect_tengjiafangyu.json',
        'resources/animation/tengjia2/effect_tengjiaranshao.json',
        'resources/animation/wuliujian/Ss_Gz_WuLiuJian.json',
        'resources/animation/xianqu/SS_eff_xianqu.json',
        'resources/animation/yexinjia/SSZBB_PJN_yexinjia.json',
        'resources/animation/yinyangyu/SS_eff_yinyangyu.json',
        'resources/animation/yinyangzhuanhuan/SZN_zhuanhuanji.json',
        'resources/animation/youxijieshu/jiesuan.json',
        'resources/animation/zhulianbihe/SS_eff_zhulianbihe.json',
    ],
    sks: [
        'resources/animation/bancountry/kaijujinpc_01.sk',
        'resources/animation/bancountry/kaijujinpc_01.png',
        'resources/animation/damage/shouji.sk',
        'resources/animation/damage/shouji.png',
        'resources/animation/losehp/kouxue.sk',
        'resources/animation/losehp/kouxue.png',
        'resources/animation/tiesuolianhuan/tiesuo02.sk',
        'resources/animation/tiesuolianhuan/tiesuo02.png',
    ],
    animations: [
        'resources/animation/dashili/dashili_jin.atlas',
        'resources/animation/dashili/dashili_qun.atlas',
        'resources/animation/dashili/dashili_shu.atlas',
        'resources/animation/dashili/dashili_wei.atlas',
        'resources/animation/dashili/dashili_wu.atlas',
        'resources/animation/dashili/dashili_ye.atlas',
        'resources/animation/equp_selected/equip_selected.atlas',
        'resources/animation/juexing_xianding_node/avatar_juexingxianding_avatar.mcc',
        'resources/animation/juexing_xianding_node/skill_name_juexing_xianding_text.mcc',
        'resources/animation/juexing_xianding_node/juexing_xianding_text.mc',
        'resources/animation/juexing_xianding_node/juexingxianding_avatar.mc',
        'resources/animation/pindianlose/pindianlose.atlas',
        'resources/animation/pindianwin/pindianwin.atlas',
        'resources/animation/shan/shan.atlas',
        'resources/animation/skill_selected/skill_selected.atlas',
        'resources/animation/zhenfa/icon/zhenfa_icon_jin.atlas',
        'resources/animation/zhenfa/icon/zhenfa_icon_qun.atlas',
        'resources/animation/zhenfa/icon/zhenfa_icon_shu.atlas',
        'resources/animation/zhenfa/icon/zhenfa_icon_wei.atlas',
        'resources/animation/zhenfa/icon/zhenfa_icon_wu.atlas',
        'resources/animation/zhenfa/jiaji/zhenfa_jiaji_jin.atlas',
        'resources/animation/zhenfa/jiaji/zhenfa_jiaji_qun.atlas',
        'resources/animation/zhenfa/jiaji/zhenfa_jiaji_shu.atlas',
        'resources/animation/zhenfa/jiaji/zhenfa_jiaji_wei.atlas',
        'resources/animation/zhenfa/jiaji/zhenfa_jiaji_wu.atlas',
        'resources/animation/zhenfa/zi/zhenfa_zi_jin.atlas',
        'resources/animation/zhenfa/zi/zhenfa_zi_qun.atlas',
        'resources/animation/zhenfa/zi/zhenfa_zi_shu.atlas',
        'resources/animation/zhenfa/zi/zhenfa_zi_wei.atlas',
        'resources/animation/zhenfa/zi/zhenfa_zi_wu.atlas',
    ],
};

export enum EntityTypeEnum {
    Toast = 'toast',
    Card = 'card',
    ViewAs = 'viewas',
    GeneralHp = 'ghp',
    Window = 'window',
    Button1 = 'btn1',
    Button2 = 'btn2',
    Line = 'line',
    Icon = 'icon',
    InfoItem = 'infoitem',
    Mark = 'mark',
    TextMark = 'textmark',
    SkillAudio = 'skillaudio',
}
