/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefabs/seat_dual_general.lh
 */
export class SeatGeneralDualBase extends Laya.GWidget {
    public img!: Laya.GImage;
    public lock!: Laya.GImage;
    public qianfu!: Laya.GImage;
    public qianfu_icon!: Laya.GImage;
}

