/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { SeatGeneral } from "./SeatGeneral";
import { SeatGeneralDual } from "./SeatGeneralDual";

/**
 * resources/prefabs/seat.lh
 */
export class SeatBase extends Laya.GWidget {
    public main!: Laya.GWidget;
    public single!: SeatGeneral;
    public general_dual!: Laya.GWidget;
    public head!: SeatGeneralDual;
    public deputy!: SeatGeneralDual;
    public fanmian!: Laya.GImage;
    public diezhi!: Laya.GImage;
    public inplayphase!: Laya.GImage;
    public inresponse!: Laya.GImage;
    public jiustate!: Laya.GImage;
    public indying!: Laya.GImage;
    public border!: Laya.Sprite;
    public diaohulishan!: Laya.GImage;
    public offline!: Laya.GImage;
    public trust!: Laya.GImage;
    public isSelected!: Laya.GImage;
    public tiesuo!: Laya.Skeleton;
    public tip_prompt!: Laya.GTextField;
    public name_bg!: Laya.GImage;
    public head_name!: Laya.GTextField;
    public deputy_name!: Laya.GTextField;
    public playername!: Laya.GTextField;
    public shield!: Laya.GImage;
    public shield_label!: Laya.GTextField;
    public hplabel!: Laya.GTextField;
    public equips!: Laya.GWidget;
    public handcard!: Laya.GImage;
    public handlabel!: Laya.GTextField;
    public camp!: Laya.GWidget;
    public kingdom!: Laya.GImage;
    public guozhan_k_mark!: Laya.GWidget;
    public guozhan_marks!: Laya.GWidget;
    public guozhan_mark_small!: Laya.GWidget;
    public s_wei!: Laya.GImage;
    public s_shu!: Laya.GImage;
    public s_wu!: Laya.GImage;
    public s_qun!: Laya.GImage;
    public s_jin!: Laya.GImage;
    public s_ye!: Laya.GImage;
    public guozhan_mark_big!: Laya.GWidget;
    public b_wei!: Laya.GImage;
    public b_shu!: Laya.GImage;
    public b_wu!: Laya.GImage;
    public b_qun!: Laya.GImage;
    public b_jin!: Laya.GImage;
    public b_ye!: Laya.GImage;
    public k_mark!: Laya.GWidget;
    public figure!: Laya.GImage;
    public rolelist!: Laya.GWidget;
    public figure_0!: Laya.GImage;
    public figure_1!: Laya.GImage;
    public figure_2!: Laya.GImage;
    public figure_3!: Laya.GImage;
    public figure_4!: Laya.GImage;
    public seat!: Laya.GImage;
    public turnstate!: Laya.GImage;
    public dizhu_score!: Laya.GTextField;
    public canClick!: Laya.GWidget;
    public rest!: Laya.GTextField;
    public skill_name!: Laya.GTextField;
    public death!: Laya.GImage;
    public think_prompt!: Laya.GTextField;
    public judges!: Laya.GBox;
    public marks!: Laya.GBox;
    public images!: Laya.GBox;
}

