/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefabs/selfseat_general.lh
 */
export class SeatSelfGeneralBase extends Laya.GWidget {
    public img!: Laya.GImage;
    public lock!: Laya.GImage;
    public qianfu!: Laya.GImage;
    public qianfu_icon!: Laya.GImage;
    public fanmian!: Laya.GImage;
    public diezhi!: Laya.GImage;
    public inplayphase!: Laya.GImage;
    public inresponse!: Laya.GImage;
    public jiustate!: Laya.GImage;
    public indying!: Laya.GImage;
    public border!: Laya.Sprite;
    public diaohulishan!: Laya.GImage;
    public isSelected!: Laya.GImage;
    public name_bg!: Laya.GImage;
    public gname!: Laya.GTextField;
    public icon!: Laya.GImage;
}

