/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefabs/seat_m_general.lh
 */
export class SeatMoGeneralBase extends Laya.GWidget {
    public img!: Laya.GImage;
    public lock!: Laya.GImage;
    public qianfu!: Laya.GImage;
    public single_qianfu_icon!: Laya.GImage;
}

