/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/scenes/Entry.lh
 */
export class EntryBase extends Laya.GWidget {
    public img!: Laya.GImage;
}

