/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

/**
 * resources/scenes/Entry.lh
 */
export class EntryBase extends Laya.GWidget {
    public img!: Laya.GImage;
    public input_username!: Laya.GTextInput;
    public input_password!: Laya.GTextInput;
    public save_info!: Laya.GButton;
    public more_settings!: Laya.GTextField;
    public btn_entry_game!: Laya.GButton;
    public title_list!: Laya.GList;
    public notice_panel!: Laya.GPanel;
    public notice!: Laya.GTextField;
    public ver!: Laya.GTextField;
    public btn_alone_server!: Laya.GButton;
    public btn_pck_mgr!: Laya.GButton;
    public btn_exit_game!: Laya.GButton;
    public btn_alone_server_1!: Laya.GButton;
}
