/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefabs/table_seat.lh
 */
export class TableSeatBase extends Laya.GWidget {
    public img!: Laya.GImage;
    public avatar!: Laya.GImage;
    public playername!: Laya.GTextField;
    public info!: Laya.GTextField;
    public state!: Laya.GImage;
    public countdown!: Laya.GImage;
    public countdown_txt!: Laya.GTextField;
}

