/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { ChatPanle } from "../../prefabs/chat/ChatPanle";

/**
 * resources/scenes/Table.lh
 */
export class TableBase extends Laya.GWidget {
    public img!: Laya.GImage;
    public players!: Laya.GWidget;
    public roomname!: Laya.GTextField;
    public roominfo!: Laya.GTextField;
    public btn_start!: Laya.GButton;
    public btn_unready!: Laya.GButton;
    public btn_ready!: Laya.GButton;
    public btn_generals!: Laya.GButton;
    public btn_hanren!: Laya.GButton;
    public btn_update_setting!: Laya.GButton;
    public btn_exit!: Laya.GButton;
    public btn_addai!: Laya.GButton;
    public btn_cards!: Laya.GButton;
    public btn_watch!: Laya.GButton;
    public chat_panle!: ChatPanle;
}

