/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefabs/general.lh
 */
export class GeneralUIBase extends Laya.GWidget {
    public img!: Laya.GImage;
    public pkgname!: Laya.GTextField;
    public border!: Laya.GImage;
    public kingdom!: Laya.GImage;
    public kingdom2!: Laya.GImage;
    public general_name!: Laya.GTextField;
    public shield!: Laya.GImage;
    public shield_label!: Laya.GTextField;
    public hps!: Laya.GList;
    public hp_label!: Laya.GTextField;
    public pkg_icon!: Laya.GImage;
    public zhulian!: Laya.GImage;
    public zhulian_zi!: Laya.GImage;
    public zhulian_selected0!: Laya.GImage;
    public zhulian_selected1!: Laya.GImage;
    public back!: Laya.GImage;
    public marks!: Laya.GList;
    public isSelected!: Laya.GImage;
    public label!: Laya.GTextField;
}

