/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefabs/general_avatar.lh
 */
export class GeneralAvatarBase extends Laya.GWidget {
    public selected!: Laya.Sprite;
    public img!: Laya.GImage;
    public general_name!: Laya.GTextField;
    public dead!: Laya.GImage;
}

