/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/room/cc_ani/shichangshi_skill.lh
 */
export class shichangshiBase extends Laya.Sprite {
    public shichangshi_bagua!: Laya.Sprite;
    public scs_effect_0!: Laya.Sprite;
    public scs_effect_1!: Laya.Sprite;
    public scs_effect_2!: Laya.Sprite;
    public scs_effect_3!: Laya.Sprite;
    public scs_effect_4!: Laya.Sprite;
    public scs_effect_5!: Laya.Sprite;
    public scs_effect_6!: Laya.Sprite;
    public scs_effect_7!: Laya.Sprite;
    public scs_effect_8!: Laya.Sprite;
    public scs_effect_9!: Laya.Sprite;
    public shichangshi_body!: Laya.Sprite;
}

