/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/room/cc_ani/shitaishici_skill.lh
 */
export class shitaishiciBase extends Laya.Sprite {
}

