/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { GeneralAvatar } from "../../prefabs/general/GeneralAvatar";
import { ChatPanle } from "../../prefabs/chat/ChatPanle";

/**
 * resources/scenes/Lobby.lh
 */
export class LobbyBase extends Laya.GWidget {
    public img!: Laya.GImage;
    public general_avatar!: GeneralAvatar;
    public playername!: Laya.GTextField;
    public list!: Laya.GList;
    public btn_loginout!: Laya.GButton;
    public btn_about!: Laya.GButton;
    public btn_settings!: Laya.GButton;
    public btn_replay!: Laya.GButton;
    public btn_cards!: Laya.GButton;
    public btn_generals!: Laya.GButton;
    public btn_create!: Laya.GButton;
    public input_serch!: Laya.GTextInput;
    public onlywait!: Laya.GButton;
    public status!: Laya.GTextField;
    public version!: Laya.GTextField;
    public chat_panle!: ChatPanle;
}

