/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefabs/chat_paopao.lh
 */
export class ChatPaoPaoBase extends Laya.GWidget {
    public txt!: Laya.GTextField;
}

