/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefabs/room_item.lh
 */
export class RoomItemBase extends Laya.GWidget {
    public roomid!: Laya.GTextField;
    public modename!: Laya.GTextField;
    public roomname!: Laya.GTextField;
    public playercount!: Laya.GTextField;
    public roomstate!: Laya.GTextField;
    public join!: Laya.GButton;
    public watch!: Laya.GButton;
    public info!: Laya.GButton;
}

