import { Gender } from '../../../core/general/general.type';

export const StandardGenerals = sgs.Package('StandardGenerals');

StandardGenerals.addGenerals([
    sgs.General({
        name: 'caocao',
        kingdom: 'wei',
        hp: 4,
        gender: Gender.Male,
        lord: true,
    }),
    sgs.General({
        name: 'simayi',
        kingdom: 'wei',
        hp: 3,
        gender: Gender.Male,
    }),
    sgs.General({
        name: 'xiahoudun',
        kingdom: 'wei',
        hp: 4,
        gender: Gender.Male,
    }),
    sgs.General({
        name: 'zhangliao',
        kingdom: 'wei',
        hp: 4,
        gender: Gender.Male,
    }),
    sgs.General({
        name: 'xuchu',
        kingdom: 'wei',
        hp: 4,
        gender: Gender.Male,
    }),
    sgs.General({
        name: 'guojia',
        kingdom: 'wei',
        hp: 3,
        gender: Gender.Male,
    }),
    sgs.General({
        name: 'zhenji',
        kingdom: 'wei',
        hp: 3,
        gender: Gender.Female,
    }),
    sgs.General({
        name: 'yangxiu',
        kingdom: 'wei',
        hp: 3,
        gender: Gender.Male,
    }),
    sgs.General({
        name: 'liubei',
        kingdom: 'shu',
        hp: 4,
        gender: Gender.Male,
        lord: true,
    }),
    sgs.General({
        name: 'guanyu',
        kingdom: 'shu',
        hp: 4,
        gender: Gender.Male,
    }),
    sgs.General({
        name: 'zhangfei',
        kingdom: 'shu',
        hp: 4,
        gender: Gender.Male,
    }),
    sgs.General({
        name: 'zhugeliang',
        kingdom: 'shu',
        hp: 3,
        gender: Gender.Male,
    }),
    sgs.General({
        name: 'zhaoyun',
        kingdom: 'shu',
        hp: 4,
        gender: Gender.Male,
    }),
    sgs.General({
        name: 'machao',
        kingdom: 'shu',
        hp: 4,
        gender: Gender.Male,
    }),
    sgs.General({
        name: 'huangyueying',
        kingdom: 'shu',
        hp: 3,
        gender: Gender.Female,
    }),
    sgs.General({
        name: 'yiji',
        kingdom: 'shu',
        hp: 3,
        gender: Gender.Male,
    }),
    sgs.General({
        name: 'sunquan',
        kingdom: 'wu',
        hp: 4,
        gender: Gender.Male,
        lord: true,
    }),
    sgs.General({
        name: 'ganning',
        kingdom: 'wu',
        hp: 4,
        gender: Gender.Male,
    }),
    sgs.General({
        name: 'lvmeng',
        kingdom: 'wu',
        hp: 4,
        gender: Gender.Male,
    }),
    sgs.General({
        name: 'huanggai',
        kingdom: 'wu',
        hp: 3,
        gender: Gender.Male,
    }),
    sgs.General({
        name: 'zhouyu',
        kingdom: 'wu',
        hp: 3,
        gender: Gender.Male,
    }),
    sgs.General({
        name: 'daqiao',
        kingdom: 'wu',
        hp: 3,
        gender: Gender.Female,
    }),
    sgs.General({
        name: 'luxun',
        kingdom: 'wu',
        hp: 3,
        gender: Gender.Male,
    }),
    sgs.General({
        name: 'sunshangxiang',
        kingdom: 'wu',
        hp: 3,
        gender: Gender.Female,
    }),
    sgs.General({
        name: 'huatuo',
        kingdom: 'qun',
        hp: 3,
        gender: Gender.Male,
    }),
    sgs.General({
        name: 'lvbu',
        kingdom: 'qun',
        hp: 4,
        gender: Gender.Male,
    }),
    sgs.General({
        name: 'diaochan',
        kingdom: 'qun',
        hp: 3,
        gender: Gender.Female,
    }),
    sgs.General({
        name: 'huaxiong',
        kingdom: 'qun',
        hp: 6,
        gender: Gender.Male,
    }),
    sgs.General({
        name: 'yuanshu',
        kingdom: 'qun',
        hp: 4,
        gender: Gender.Male,
    }),
    sgs.General({
        name: 'gongsunzan',
        kingdom: 'qun',
        hp: 4,
        gender: Gender.Male,
    }),
]);
