/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefabs/card.lh
 */
export class CardBase extends Laya.GWidget {
    public img!: Laya.GImage;
    public suit!: Laya.GImage;
    public num!: Laya.GImage;
    public color!: Laya.GImage;
    public cardName!: Laya.GTextField;
    public back!: Laya.GImage;
    public marks!: Laya.GList;
    public viewas!: Laya.GImage;
    public viewas_name!: Laya.GTextField;
    public viewas_number!: Laya.GImage;
    public viewas_suit!: Laya.GImage;
    public isSelected!: Laya.GImage;
    public label!: Laya.GTextField;
}

