/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/scenes/Load.lh
 */
export class LoadBase extends Laya.GWidget {
    public img!: Laya.GImage;
    public pb!: Laya.GProgressBar;
    public txt!: Laya.GTextField;
}

